# -*- coding: utf-8 -*-
"""data visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_bfcfgU31yHawmk-9QwGb-4s920Op26

DATA VISUALIZATION
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

import pandas as pd
df = pd.read_csv('/content/large_customer_churn_dataset.csv')
sns.countplot(x="Churn", data=df)
plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Count")
plt.show()

sns.boxplot(x="Churn", y="MonthlyCharges", data=df)
plt.title("Monthly Charges vs Churn")
plt.show()

sns.boxplot(x="Churn", y="Tenure", data=df)
plt.title("Customer Tenure vs Churn")
plt.show()

sns.countplot(x="ContractType", hue="Churn", data=df)
plt.title("Contract Type vs Churn")
plt.show()

sns.countplot(x="InternetService", hue="Churn", data=df)
plt.title("Internet Service vs Churn")
plt.show()

sns.countplot(x="PaymentMethod", hue="Churn", data=df)
plt.title("Payment Method vs Churn")
plt.xticks(rotation=30)
plt.show()

sns.countplot(x="City", hue="Churn", data=df)
plt.title("City-wise Customer Churn")
plt.xticks(rotation=30)
plt.show()

corr = df[["Age", "Tenure", "MonthlyCharges"]].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

sample_df = df.sample(2000)

sns.pairplot(sample_df, hue="Churn")
plt.show()

"""Advanced Plot (Churn Rate %)"""

churn_rate = df.groupby("ContractType")["Churn"].value_counts(normalize=True).unstack()

churn_rate.plot(kind="bar", stacked=True)
plt.title("Churn Rate by Contract Type (%)")
plt.ylabel("Proportion")
plt.show()

"""Data Story
The visual analysis reveals that customer churn is strongly influenced by monthly charges, tenure, and contract type. Customers with higher billing and shorter tenure are more likely to leave. Monthly contract users exhibit the highest churn rate, while long-term contracts contribute to customer retention. Regional and payment-based variations also provide additional business insights.
"""