# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WR1hSvnuyunVmfFU9uO0K50-v9HeMauh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("large_customer_churn_dataset.csv")

print("Dataset Loaded Successfully")

df.head()

print("Shape:", df.shape)
print("\nColumns:", df.columns)
df.info()

df.isnull().sum()

df.describe()

df["Churn"].value_counts()

"""**bold text**  Ask Business Questions (WRITE IN REPORT)
Do high-paying customers churn more?
Does tenure affect churn?
Which contract type causes churn
"""

df.groupby("Churn")["MonthlyCharges"].mean()
df.groupby("Churn")["Tenure"].mean()

sns.countplot(x="Churn", data=df)
plt.title("Churn Distribution")
plt.show()

sns.boxplot(x="Churn", y="MonthlyCharges", data=df)
plt.title("Monthly Charges vs Churn")
plt.show()

sns.boxplot(x="Churn", y="Tenure", data=df)
plt.title("Tenure vs Churn")
plt.show()

sns.countplot(x="ContractType", hue="Churn", data=df)
plt.title("Contract Type vs Churn")
plt.show()

sns.countplot(x="InternetService", hue="Churn", data=df)
plt.title("Internet Service vs Churn")
plt.show()

sns.countplot(x="PaymentMethod", hue="Churn", data=df)
plt.title("Payment Method vs Churn")
plt.xticks(rotation=30)
plt.show()

corr = df[["Age", "Tenure", "MonthlyCharges"]].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

sns.boxplot(x=df["MonthlyCharges"])
plt.title("Outliers in Monthly Charges")
plt.show()

"""**bold text**  Final Insights
Customers with high monthly charges are more likely to churn
Customers with low tenure show higher churn
Monthly contract users churn the most
Long-term contracts reduce churn
Dataset is large and suitable for real-world analysis
"""